version: '3'

services:
  ghost:
    image: ghost:alpine
    container_name: some-ghost
    environment:
      - NODE_ENV=development
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=mysecretpassword
      - database__connection__database=ghost
    ports:
      - "8080:2368"
    volumes:
      - /path/to/ghost/blog:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: ghost-db
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=mysecretpassword
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
